# Generated by Django 4.2.16 on 2026-04-18 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhaleTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(db_index=True, max_length=66, unique=True)),
                ('block_number', models.BigIntegerField()),
                ('from_address', models.CharField(max_length=42)),
                ('to_address', models.CharField(max_length=42)),
                ('token_symbol', models.CharField(default='USDC', max_length=20)),
                ('token_amount', models.DecimalField(decimal_places=6, max_digits=30)),
                ('usd_value', models.DecimalField(decimal_places=2, max_digits=30)),
                ('timestamp', models.DateTimeField()),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Whale Transaction',
                'verbose_name_plural': 'Whale Transactions',
                'ordering': ['-timestamp'],
            },
        ),
    ]
